
server:
  port: 9999

spring:
  profiles:
    active: pro
  servlet:
    multipart:
      max-file-size: 10MB # 单文件上传最大10m
      max-request-size: 100MB # 单次上传最大100m
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1

# 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    com.heycm.mapper: DEBUG

# 自定义配置变量
heycm:
  system:
    openApi: /**/open/** # 应用开放接口
  jwt:
    privateKey: com.heycm.crim # JWT签名私钥
    ttl: 1800 # JWT签名过期时间，秒
  shiro:
    rememberMeMaxAge: 86400 # 记住我时长（秒）
    rememberMeCipherKey: 3AvVhmFLUs0KTA3Kprsdag==
  zhenziSms: # 榛子云短信
    apiUrl: https://sms_developer.zhenzikj.com
    appId: 104324
    appSecret: d7f83c86-4cb1-4ec0-8a2a-1eb0577a0abc
    validTime: 10 # 有效时间，分钟
  aliyun:
    oss:
      endPoint: oss-cn-beijing.aliyuncs.com
      accessKeyID: LTAI4GEvxoPe8YRYEmzqvV6S
      accessKeySecret: Yo2qQkBt1tb8XEeOynh7FCjXdft4Q8
      imgBucketName: crim-img
      imgHost: https://crim-img.oss-cn-beijing.aliyuncs.com
      imgDir: images
      fileBucketName: crim-file
      fileDir: files